<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EOD Report - {{ $eodReport->eod_date->format('d/m/Y') }}</title>
    <style>
        @page {
            margin: 20mm;
        }
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #000;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .font-bold { font-weight: bold; }
        .divider { border-top: 1px solid #000; margin: 10px 0; }
        .header { margin-bottom: 15px; }
        .row { display: flex; justify-content: space-between; padding: 3px 0; }
        .mt-1 { margin-top: 8px; }
        .mt-2 { margin-top: 15px; }
        .mb-1 { margin-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 6px 8px; text-align: left; border-bottom: 1px solid #ddd; font-size: 11px; }
        th { background: #f0f0f0; font-weight: bold; text-transform: uppercase; font-size: 10px; }
        .section-title { font-size: 14px; font-weight: bold; margin: 15px 0 8px 0; padding-bottom: 4px; border-bottom: 2px solid #333; }
        .summary-box { background: #f9f9f9; padding: 10px; border-radius: 4px; margin-bottom: 10px; }
        .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }
        .summary-item { text-align: center; padding: 8px; background: #f5f5f5; border-radius: 4px; }
        .summary-value { font-size: 18px; font-weight: bold; }
        .summary-label { font-size: 10px; text-transform: uppercase; color: #666; }
        .diff-negative { color: #dc2626; }
        .diff-positive { color: #16a34a; }

        @media print {
            body { padding: 0; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="background: #f4f4f4; padding: 10px; margin-bottom: 20px; text-align: center; border-radius: 4px;">
        <button onclick="window.print()" style="padding: 10px 20px; cursor: pointer; background: #000; color: #fff; border: none; border-radius: 5px; font-weight: bold;">PRINT REPORT</button>
        <button onclick="window.close()" style="padding: 10px 20px; cursor: pointer; background: #ccc; color: #000; border: none; border-radius: 5px; margin-left: 10px;">CLOSE</button>
    </div>

    <div class="header text-center">
        <h2 style="margin: 0;">{{ $eodReport->store->name ?? 'Store' }}</h2>
        <div style="font-size: 14px; font-weight: bold; margin-top: 5px;">END OF DAY REPORT</div>
        <div style="font-size: 12px;">{{ $eodReport->eod_date->format('d F Y') }}</div>
    </div>

    <div class="divider"></div>

    <div class="row">
        <span>Generated By:</span>
        <span>{{ $eodReport->generatedBy?->name ?? 'Unknown' }}</span>
    </div>
    <div class="row">
        <span>Generated At:</span>
        <span>{{ $eodReport->created_at->format('d/m/Y H:i') }}</span>
    </div>
    <div class="row">
        <span>Status:</span>
        <span style="text-transform: uppercase; font-weight: bold;">{{ $eodReport->status }}</span>
    </div>

    <div class="section-title">Sales Summary</div>
    <div class="summary-grid">
        <div class="summary-item">
            <div class="summary-label">Transactions</div>
            <div class="summary-value">{{ number_format($eodReport->total_transactions) }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Gross Sales</div>
            <div class="summary-value">Rp {{ number_format($eodReport->total_sales, 0, ',', '.') }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Net Sales</div>
            <div class="summary-value">Rp {{ number_format($eodReport->total_net_sales, 0, ',', '.') }}</div>
        </div>
    </div>

    <div class="section-title">Payment Breakdown</div>
    <div class="row">
        <span>Cash</span>
        <span class="font-bold">Rp {{ number_format($eodReport->sales_cash, 0, ',', '.') }}</span>
    </div>
    <div class="row">
        <span>QRIS</span>
        <span class="font-bold">Rp {{ number_format($eodReport->sales_qris, 0, ',', '.') }}</span>
    </div>
    <div class="row">
        <span>Debit</span>
        <span class="font-bold">Rp {{ number_format($eodReport->sales_debit, 0, ',', '.') }}</span>
    </div>
    <div class="row">
        <span>Credit</span>
        <span class="font-bold">Rp {{ number_format($eodReport->sales_credit, 0, ',', '.') }}</span>
    </div>

    <div class="section-title">Discounts & Deductions</div>
    <div class="row">
        <span>Promo Discount</span>
        <span>- Rp {{ number_format($eodReport->total_promo_discount, 0, ',', '.') }}</span>
    </div>
    <div class="row">
        <span>Points Discount</span>
        <span>- Rp {{ number_format($eodReport->total_points_discount, 0, ',', '.') }}</span>
    </div>
    <div class="row">
        <span>Tier Discount</span>
        <span>- Rp {{ number_format($eodReport->total_tier_discount, 0, ',', '.') }}</span>
    </div>
    <div class="row">
        <span>Voucher Discount</span>
        <span>- Rp {{ number_format($eodReport->total_voucher_discount, 0, ',', '.') }}</span>
    </div>
    <div class="row">
        <span>Tax</span>
        <span>Rp {{ number_format($eodReport->total_tax, 0, ',', '.') }}</span>
    </div>
    <div class="row">
        <span>Expenses</span>
        <span>Rp {{ number_format($eodReport->total_expenses, 0, ',', '.') }}</span>
    </div>

    <div class="section-title">Cash Reconciliation</div>
    <div class="summary-grid">
        <div class="summary-item">
            <div class="summary-label">Expected Cash</div>
            <div class="summary-value">Rp {{ number_format($eodReport->total_expected_cash, 0, ',', '.') }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Actual Cash</div>
            <div class="summary-value">Rp {{ number_format($eodReport->total_actual_cash, 0, ',', '.') }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Difference</div>
            @if($eodReport->cash_difference < 0)
                <div class="summary-value diff-negative">- Rp {{ number_format(abs($eodReport->cash_difference), 0, ',', '.') }}</div>
            @else
                <div class="summary-value diff-positive">Rp {{ number_format($eodReport->cash_difference, 0, ',', '.') }}</div>
            @endif
        </div>
    </div>
    <div class="mt-1" style="font-size: 11px; color: #666;">Total Shift Closings: {{ $eodReport->total_closings }}</div>

    <div class="section-title">Products Sold</div>
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th style="text-align: center;">Qty Sold</th>
                <th style="text-align: right;">Revenue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($eodReport->items->sortByDesc('total_qty_sold') as $item)
            <tr>
                <td>{{ $item->product->name }}</td>
                <td style="text-align: center;">{{ number_format($item->total_qty_sold) }}</td>
                <td style="text-align: right;">Rp {{ number_format($item->total_revenue, 0, ',', '.') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    @if($eodReport->purchaseOrders->count() > 0)
    <div class="section-title">Auto-Generated Purchase Orders</div>
    <table>
        <thead>
            <tr>
                <th>PO Number</th>
                <th>Supplier</th>
                <th style="text-align: right;">Total</th>
                <th style="text-align: center;">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($eodReport->purchaseOrders as $po)
            <tr>
                <td>{{ $po->po_number }}</td>
                <td>{{ $po->supplier->name }}</td>
                <td style="text-align: right;">Rp {{ number_format($po->total_amount, 0, ',', '.') }}</td>
                <td style="text-align: center; text-transform: uppercase;">{{ $po->status }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if($eodReport->notes)
    <div class="section-title">Notes</div>
    <div style="padding: 8px; background: #f9f9f9; border-radius: 4px;">{{ $eodReport->notes }}</div>
    @endif

    <div class="divider mt-2"></div>
    <div class="text-center" style="font-size: 10px; color: #666; margin-top: 10px;">
        Printed at: {{ now()->format('d/m/Y H:i:s') }}
    </div>

    <script>
        window.onload = function() { window.print(); }
    </script>
</body>
</html>
