<?php

namespace App\Console\Commands;

use App\Jobs\SyncBackupToCloud;
use App\Models\Backup;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class BackupCreate extends Command
{
    protected $signature = 'backup:create {--no-sync : Skip cloud sync} {--store-id= : Store ID for multi-tenant}';

    protected $description = 'Buat backup database dan sync ke cloud';

    public function handle()
    {
        $this->info('Memulai backup database...');

        try {
            $connection = config('database.default');
            $timestamp = now()->format('Y-m-d_His');
            $filename = "backup_{$timestamp}";

            $backupDir = storage_path('app/backups');
            if (! is_dir($backupDir)) {
                mkdir($backupDir, 0755, true);
            }

            if ($connection === 'sqlite') {
                $dbPath = database_path('database.sqlite');
                if (! file_exists($dbPath)) {
                    $this->error('File database tidak ditemukan.');

                    return 1;
                }
                $ext = '.sqlite';
                $dest = "{$backupDir}/{$filename}{$ext}";
                copy($dbPath, $dest);
            } else {
                $host = config('database.connections.mysql.host');
                $port = config('database.connections.mysql.port');
                $db = config('database.connections.mysql.database');
                $user = config('database.connections.mysql.username');
                $pass = config('database.connections.mysql.password');

                $cmd = sprintf(
                    'mysqldump --host=%s --port=%s --user=%s --password=%s --single-transaction --routines --triggers %s 2>&1',
                    escapeshellarg($host),
                    escapeshellarg($port),
                    escapeshellarg($user),
                    escapeshellarg($pass),
                    escapeshellarg($db)
                );

                $output = null;
                $code = null;
                exec($cmd, $output, $code);

                if ($code !== 0) {
                    $this->error('mysqldump gagal, fallback ke PHP dump...');
                    $tables = DB::select('SHOW TABLES');
                    $dbName = config('database.connections.mysql.database');
                    $key = "Tables_in_{$dbName}";
                    $sql = '-- Generated by POS Backup at '.now()."\n\n";

                    foreach ($tables as $table) {
                        $tableName = $table->$key;
                        $sql .= "DROP TABLE IF EXISTS `{$tableName}`;\n";
                        $create = DB::select("SHOW CREATE TABLE `{$tableName}`");
                        $sql .= $create[0]->{'Create Table'}.";\n\n";
                        $rows = DB::table($tableName)->get();
                        foreach ($rows as $row) {
                            $values = collect((array) $row)->map(fn ($v) => is_null($v) ? 'NULL' : "'".addslashes($v)."'")->implode(', ');
                            $sql .= "INSERT INTO `{$tableName}` VALUES ({$values});\n";
                        }
                        $sql .= "\n";
                    }
                    $output = [$sql];
                }

                $ext = '.sql';
                $dest = "{$backupDir}/{$filename}{$ext}";
                file_put_contents($dest, implode("\n", $output));
            }

            $fullFilename = $filename.$ext;

            $record = Backup::create([
                'filename' => $fullFilename,
                'disk' => 'local',
                'path' => 'backups/'.$fullFilename,
                'size' => filesize($dest),
                'checksum' => hash_file('sha256', $dest),
                'status' => 'pending',
                'notes' => 'Dibuat via scheduler',
            ]);

            $this->info('Backup berhasil: '.$fullFilename.' ('.number_format(filesize($dest) / 1024, 1).' KB)');

            if (! $this->option('no-sync')) {
                SyncBackupToCloud::dispatch($record->id);
                $this->info('Job sync cloud telah di-dispatch.');
            }

            Log::info('Backup created via command: '.$fullFilename);

            return 0;
        } catch (\Exception $e) {
            $this->error('Gagal: '.$e->getMessage());
            Log::error('Backup command failed: '.$e->getMessage());

            return 1;
        }
    }
}
